### PR TITLE
Copy buildroot config with other artifacts

### PR DESCRIPTION
**Pull request by montjoie**
For debugging, it is helpfull to have final config along with rootfs.
So after build let's copy buildroot config.

### CODE REVIEW

**Review by mgalka — APPROVED** [review]
looks good

**Comment by mgalka** [comment]
@montjoie Could you please clarify if the goal of this change was to just copy the config file to the `images` directory or was it supposed to include the file in the produced images?

**Comment by montjoie** [comment]
The goal was to copy only the ".config" file

**Comment by gctucker** [comment]
> The goal was to copy only the ".config" file

Does the config file need to be in the image files?  Is the intent to be able to get the config file back from any buildroot image?

**Comment by montjoie** [comment]
The goal is to be able to check how was built a rootfs.
Typically, it could have helped on https://github.com/kernelci/buildroot/pull/10

**Comment by gctucker** [comment]
Do you want the buildroot config file to be uploaded to storage.kernelci.org or part of the rootfs images themselves?

I think having it on storage would be fine, but it depends whether we want to be able to use it at runtime in test jobs too.

**Review by gctucker — COMMENTED** [review]
The config file was not uploaded with the image files for some reason:
https://storage.staging.kernelci.org/images/rootfs/buildroot/buildroot-baseline/20211201.1/

It's worth checking what is being done in kci_rootfs and in the Jenkins rootfs builder job.

**Review by gctucker — APPROVED** [review]
Tested OK on staging:
https://storage.staging.kernelci.org/images/rootfs/buildroot/buildroot-baseline/20220322.1/x86/

The new buildroot job based on `kci_rootfs` and a generic upload step in Jenkins has solved the issue as all the artifacts are now uploaded.

**Pull request merged**
