### PR TITLE
Update bootrr commit

### PR DESCRIPTION
**Pull request by mgalka**
bootrr: Include bootrr tests for online cpus in production builds.

### CODE REVIEW

**Comment by mgalka** [comment]
Tested locally. Works fine

**Comment by gctucker** [comment]
Please drop the `STAGING` patch so we can merge this.  Also we'll need the updated checksum for the generated source tarball.

**Comment by mgalka** [comment]
> Please drop the `STAGING` patch so we can merge this. Also we'll need the updated checksum for the generated source tarball.

I don't think I know where I should put the checksum

**Comment by gctucker** [comment]
Try to build the rootfs image locally and it'll complain about a mismatch with what is in `package/bootrr/bootrr.hash`.

**Comment by mgalka** [comment]
Fixed the hash and removed surplus "STAGING" commit

**Review by gctucker — APPROVED** [review]
Great, now we should be able to make some production images.

**Pull request merged**
