### PR TITLE
T16462 baseline dmesg

### PR DESCRIPTION
**Pull request by gctucker**
The baseline rootfs has the `dmesg` implementation from `busybox` which supports very minimal command line options.  As the `baseline` test plan should be checking for kernel errors in the log, using the standard `dmesg` from `util-linux` is needed.

This PR provides one solution to do this, but as there aren't any `buildroot` config options to disable dmesg in busybox and build only dmesg from util-linux, it's half-way between hacks and a proper solution.  It should be good enough to be used by KernelCI but not to send upstream in its current state.

This was tested with a LAVA job definition to create some test cases based on dmesg:
https://lava.collabora.co.uk/scheduler/job/1805080

### CODE REVIEW

**Review by khilman — APPROVED** [review]

**Comment by khilman** [comment]
LGTM, but any reason we shouldn't move to a minimal debian rootfs for `baseline`?  Is it just because we have more arch coverage with buildroot still?

**Comment by gctucker** [comment]
@khilman I did the comparison, and using Debian means a larger file system and longer time to boot.  As `baseline` is meant to replace the current boots and be run on every single platform, download size and boot time are crucial.

**Comment by khilman** [comment]
Sounds right.  Combined with the fact that debian doesn't exist (yet) for some of the recently added arches (arc, riscv) makes sense to stick with buildroot.

**Comment by gctucker** [comment]
OK thanks for the review.  Once the dust has settled we can revisit this and the bootrr package to see if we can come up with a more upstream-friendly solution and maybe even upstream some of that to reduce the number of patches we carry.

**Pull request merged**
